### PR TITLE
allow Symfony 7

### PR DESCRIPTION
**Pull request by tacman**
plus removes unmaintained versions of dependencies.

### CODE REVIEW

**Comment by xyNNN** [comment]
Thanks @tacman 

I would like to create a new minor release for the upcoming changes of the PHP version from (8.0.x to 8.1.x).

What do you think=

**Comment by tacman** [comment]
Yes, I think that'd be great.  Also, how about moving to github actions and dropping travis?

**Comment by xyNNN** [comment]
> Yes, I think that'd be great. Also, how about moving to github actions and dropping travis?

Great idea but currently I've no time to maintain this project. If you're interested I'm happy if somebody can takeover it.
Release will be following shortly.

**Comment by hiddeb** [comment]
Will this PR be merged anytime soon?

**Comment by xyNNN** [comment]
@hiddeb https://github.com/xyNNN/GoogleTagManagerBundle/releases/tag/3.2.0

**Comment by hiddeb** [comment]
> @hiddeb https://github.com/xyNNN/GoogleTagManagerBundle/releases/tag/3.2.0

Thanks for the merge, I created another PR with support for Symfony 7.1

**Comment by xyNNN** [comment]
https://github.com/xyNNN/GoogleTagManagerBundle/releases/tag/3.2.1 @hiddeb

**Pull request merged**
