### PR TITLE
extending ContainerAware is deprecated since symfony version 2.8

### PR DESCRIPTION
**Pull request by toooni**

### CODE REVIEW

**Comment by xyNNN** [comment]
Sorry, I've missed this pull request. Do you think it makes sense to update the version constraint of the symfony components to greater than 2.8 and create a new release for this update to prevent breaking changes? If yes, could you update the constraints in the composer.json?

Thank you @toooni

**Comment by xyNNN** [comment]
I've fixed the failed tests on Travis CI in the current master branch. Could you rebase your pull request? ;)
See my commit https://github.com/xyNNN/GoogleTagManagerBundle/commit/13da7110a98f2452c744b54360aef4daaa6eec49

**Comment by toooni** [comment]
@xyNNN i rebased the PR and added the symfony constraints (which totally makes sense, sorry). I took the liberty to change the package version in readme to version ~2.0 - You can tell if you want to change this.

**Comment by xyNNN** [comment]
Great! Thank you very much @toooni - I will prepare the new release today in the evening!

**Pull request merged**
